"""add seat_count to booking_requests

Revision ID: 3239fbba0862
Revises: b89c97ee9048
Create Date: 2026-09-22 15:19:41.819625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3239fbba0862'
down_revision: Union[str, Sequence[str], None] = 'b89c97ee9048'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'booking_requests',
        sa.Column('seat_count', sa.Integer(), nullable=False, server_default='1'),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_requests', 'seat_count')
    # ### end Alembic commands ###
