"""add seat_requested to booking_requests

Revision ID: 9552b220d3f4
Revises: 0c6e42a7507e
Create Date: 2026-09-20 20:18:06.911084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9552b220d3f4'
down_revision: Union[str, Sequence[str], None] = '0c6e42a7507e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column(
        'booking_requests',
        sa.Column(
            'seat_requested',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking_requests', 'seat_requested')
    # ### end Alembic commands ###
