"""add temp test field

Revision ID: ed07e72dfa21
Revises: 80196ed2dbd0
Create Date: 2026-09-20 01:22:23.963692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed07e72dfa21'
down_revision: Union[str, Sequence[str], None] = '80196ed2dbd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temp_test_field', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temp_test_field')
    # ### end Alembic commands ###
