"""remove temp test field

Revision ID: f26379721208
Revises: ed07e72dfa21
Create Date: 2026-09-20 01:26:43.797492

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f26379721208'
down_revision: Union[str, Sequence[str], None] = 'ed07e72dfa21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temp_test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temp_test_field', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
